name: Test DongatoS.A.S App
on:
  push:
    branches:
    - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Install dependencies frontend
      run: |
        cd dongato-frontend
        npm install
    - name: Install selenium-side-runner
      run: |
        cd dongato-frontend
        npm install -g selenium-side-runner
    - name: |
        cd dongato-frontend
        Install chromedriver
      run: |
        cd dongato-frontend
        npm install -g chromedriver
    - name: Start server frontend
      run: |
        cd dongato-frontend
        npm run dev &
    - name: Run BB tests with selenium-side-runner
      run: |
        cd dongato-frontend
        selenium-side-runner src/tests/*.side
    - name: Run unit tests
      run: |
        cd dongato-frontend
        npm run test:unit with jest
    - name: Install dependencies backend
      run: |
        cd dongato-backend
        npm install
    - name: Run sonarQube test
      run: |
        cd dongato-backend
        npm run sonar &


      
